# Generated by Django 3.2.6 on 2025-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250418_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='ownerId',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='robot',
            name='cameraFront',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='cameraTop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='healthStatus',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='robot',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='modelName',
            field=models.CharField(choices=[('mercedes', 'Mercedes'), ('cheverolet', 'Cheverolet'), ('toyota', 'Toyota'), ('tesla', 'Tesla')], max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='robotId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
