# Generated by Django 3.2.6 on 2025-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250418_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianalytic',
            old_name='robot_id',
            new_name='robot',
        ),
        migrations.AddField(
            model_name='aianalytic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_analytics/'),
        ),
        migrations.AddField(
            model_name='aianalytic',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aianalytic',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
