# Generated by Django 3.2.6 on 2025-05-07 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20250419_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('dest_latitude', models.FloatField()),
                ('dest_longitude', models.FloatField()),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('failure_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.robot')),
            ],
        ),
    ]
