# Generated by Django 3.2.6 on 2025-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20250507_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalytic',
            name='alert_latitude',
            field=models.FloatField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='aianalytic',
            name='alert_longitude',
            field=models.FloatField(null=True, default=None),
        ),
    ]
