# Generated by Django 3.2.6 on 2025-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250507_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalytic',
            name='alert_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='aianalytic',
            name='alert_longitude',
            field=models.FloatField(null=True),
        ),
    ]
