# Generated by Django 3.2.6 on 2025-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalytic',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='aianalytic',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
