# Generated by Django 3.2.6 on 2025-05-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20250507_0205'),
        ('home', '0009_auto_20250507_0206'),
    ]

    operations = [
    ]
