# Generated by Django 3.2.6 on 2025-05-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_0008_auto_20250507_0205_0009_auto_20250507_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalytic',
            name='alert_latitude',
        ),
        migrations.RemoveField(
            model_name='aianalytic',
            name='alert_longitude',
        ),
    ]
